apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-ulrpvl3c8hr33
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-ulrpvl3c8hr33
    app.kubernetes.io/part-of: test-gitlabrenovate-qrae1sqponyt5
  name: component-ulrpvl3c8hr33
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-ulrpvl3c8hr33
status:
  loadBalancer: {}
